language: python
python: 3.7

jobs:
  include:
    - if: branch = master__old_code
      env: TOXENV=py37-master
      after_success: codecov
    - if: branch != master__old_code
      env: TOXENV=py37-dev
      after_success: codecov
    - env: TOXENV=build
    - stage: Deploy to Test PyPI release
      env: TOXENV=build
      before_script: sed -i -E "s/^([0-9]+\.[0-9]+\.[0-9]+)$/\1.$TRAVIS_BUILD_NUMBER/" version.txt
      deploy:
        distributions: skip
        skip_cleanup: true
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: "__token__"
        password:
          secure: "aplcJFk6DBidZ7kWgLgsjg4fSxTnYUcaPiCKbOwuLe2JQmmRTmCF2P7j24K2bWqe/zcDZLwhQtq/KJ76NcjeGc2K8hvXhpq6MaciQdQPuvNY32T+H708aE/oCBuIlpafBsJgqrF0e0Q+7wHSwvENgmuDZTcc1fEPWXYJ3rwnRg4jFIVfQkS9sJylen8zIjBFGTFBpGo5b3y93ksSBMmTc4/lxuH5012RsKktApRtPpPU4Rlio6xGlDexR5QbHO6lFt7SZUsgtsl0hp7zbBRc4YBiYBr5op4O+Fs7z3xaa2xZb7aPCKcHi9sx2N6aN/UCiQ4dQnWX6wM6nsXhMYe/3uigOd7p18mlYaDKJD7ejl/THgLX1hn65mYkrso6ELBR+G38O+KerdY8jy40itgO1H9a4aChYjZjywS3hUc5Wf816AyEo1CsEMIzOINUgQKrVsh4LGWVz+EBr044V3gFRXIYQz/BcDmWrFqRY9+r3PIjd6gXxaMq8pA2rmTrCYiHWyWKjT/i0D2+B8ZP1rxeBIvHfGhIIoOPqYrjGaumh4SoTnW+WO40b1Hbi/6Cnlk7SUV1XsB9YCD3gWnHCr2158cbhI0CBTX5XNT++rT4SFfThMcfgX5DJ44UJQG/+lOgKpuJ/6N//epLFTH0qcgEKt18BamSb+rtKjBOOkLG02A="
        on:
          branch: dev
    - stage: Deploy to PyPI release
      env: TOXENV=build
      python: 3.8
      deploy:
        distributions: skip
        skip_cleanup: true
        provider: pypi
        user: "__token__"
        password:
          secure: "baIRwF9J73YpU1mrRuGoKTAsXO8vSVuhCVxbQT8G6UDhJw5SwYQI80M14+F+9a4ieamKwKyux3HtTXYt12M0bWnqfIyYzdwgy7EHs5nC5C5mM2XCOcJWxbTm7swk1SS1aCajDZyMkMoLZdoVCCB5dyUh7SMocBr6JQzJ9bX5veoedKHkUF0+vZtfkQWZF8Ev9h/91emagR6tgzHRwpXqQE32aIiSjy4KVDcEZCjqnrAwoQn/QBFPhfh31S3ACYXCrvbhds3bwB3DXIPDyfMZ5fY20cO1SV+c0Rx7UtwNAHp0bZZplHvFTPP1pWORCWh1o+nF30CEASedwTQ93GHeeFCT9zJDyv0nfNBQmbMYDe3dIIaAFFl0cSTlzTH0P01tsghA1H5nnGBX7SnGwY8PJSTpHc1HZ668FtbjNqDANG+TSHyIP+DCidBiu2atnJBINAM8+ZLDPPKdsf4zoXlEdMaiQSaoJT82p2ExqKfPX75bfVsdj+J8rmsRPwFuacYf3+9zdNVMVwiF3stOmLKAMGqPTntUM5ZYBXaC8PAbBlSn+/z9AaNuVt7qBCaeOOMPdP9lrgAqI6qOwpYSRcr0PuERVb+uKXbBpn5j7szhWz0NTVPwbQGfHtt5Vhc2GvfKzBVRTSXCgHYVcalxSYa9cAt1O0VgUomGvjl7RTfoMWQ="
        on:
          tags: true
    - stage: Create GitHub release
      env: TOXENV=build
      before_deploy:
        - export AUTHOR_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
        - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
        - export GIT_TAG="$(cat version.txt | tr -d ' \t\n\r')"
        - git config --local user.name $AUTHOR_NAME
        - git config --local user.email $AUTHOR_EMAIL
        - git tag $GIT_TAG
      deploy:
        provider: releases
        skip_cleanup: true
        draft: true
        api_key:
          secure: "KbhEeNcELMwAnU8bqFsmrh3CPHGBMBeciFAkf3fn4Xr2oROmq+dVs/JtUwAnL/MzhI7EuXBw18txMO1xpZyOwpSN+0bTOHLnjF4k7vDUs8MLr0TrpxB5pi9CB4gFlo7NhGP5M5XTHFNmWfEha29xxzgRFGJXIj+w34zUsiqXiuB7LrOeSSssPGZ8x1yzFAUi62IibnHkOr1HeRWaF8W2ei4DsNbvaCkdKG6kz0+AB6JOpKaE/2KkxocpJbaj4G8WO6qvdQARgQGYWJ980i4X59N/b7tcXC1TLTnpo6R7j98mrtzYEcAWtmoznBHwXrhb2qrNEhYXBv3aWQfugd5Et/zCzkUysOTx6z9yAuoldiUeiG7zYNHM0jjY0s7iBItkuB+myzWt0IzWF84Kg90XUtMIeICCY4HJp5Mt8U1QQiknUVvDuQOYp2wFEPwB5WiCio+ImjHRm5+5I3wWaY92qRlTvGXpQfltvfzy2Qoz3ovr758zvVuD+D0R/2vrnx+6dqM0PmIFTgIJbVt7/IlOTVwg5iy+DI2ASqTNu6086UsIv8ibjcZ56SVOtlSkK1wQInKStfAzIbJnDYBiyMUe+c9O9yCy2/T/UO+oeaQofEraOX9vQFUl3ahn3H+8wKSbdY/7N3RVFo71S1cjUtpcSyd7O+eCyP8lMP/ZQOGtDzU="
        file_glob: true
        file: dist/*
        name: cloudshell-cp-vcenter $GIT_TAG
        target_commitish: master__old_code
        on:
          branch: master__old_code
    - stage: Check version
      language: bash
      install:
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout -qf $TRAVIS_PULL_REQUEST_BRANCH
      script: "! git diff --exit-code --quiet origin/master__old_code version.txt"

install:
  - pip install tox
  - pip install codecov

script: tox

stages:
  - name: Check version
    if: branch = master__old_code AND type = pull_request
  - name: Test
  - name: Deploy to Test PyPI release
    if: branch = dev AND type != pull_request
  - name: Create GitHub release
    if: branch = master__old_code AND type != pull_request
  - name: Deploy to PyPI release
    if: tag IS present
